// pages/index.tsx or components/NFTGrid.tsx
import React from "react";
import NFTCard from "./NFTCard";

const nftItems = [
  // This data would actually come from your backend or a service
  {
    category: "Machine Learning Models",
    imageUrl: "/images/Dataset.png",
    priceInETH: "0.5 ETH",
    creator: "DataScience Inc.",
    title: "Predictive Analysis Model",
    basicInfo: "A sophisticated model for financial forecasting.",
  },
  {
    category: "AI Artwork",
    imageUrl: "/images/Dataset.png",
    priceInETH: "1.2 ETH",
    creator: "Artificial Creations",
    title: "Digital Dreamscape",
    basicInfo: "A unique piece of art generated by a neural network.",
  },
  {
    category: "Natural Language Processing Tools",
    imageUrl: "/images/Dataset.png",
    priceInETH: "0.8 ETH",
    creator: "NLP Masters",
    title: "Text Summarizer Pro",
    basicInfo: "An advanced tool for summarizing large texts.",
  },
  {
    category: "Autonomous Vehicle Simulation",
    imageUrl: "/images/Dataset.png",
    priceInETH: "1.5 ETH",
    creator: "Futuristic Tech Labs",
    title: "Urban Traffic AI Simulator",
    basicInfo:
      "An advanced simulation tool for testing and improving autonomous vehicle navigation in urban environments.",
  },

  // ... more items
];
const NFTGrid: React.FC = () => {
  return (
    <div style={{ display: "flex", gap: "1rem" }}>
      {nftItems.map((item, index) => (
        <NFTCard key={index} {...item} />
      ))}
    </div>
  );
};

export default NFTGrid;
